import { useState } from "react";
import { IoDownloadOutline, IoDocumentTextOutline } from "react-icons/io5";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from "recharts";
import PageLayout from "../components/layout/PageLayout";
import ChartCard from "../components/ChartCard";
import { useData } from "../context/DataContext";
import { monthlyRevenue, monthlyComparison, revenueByServiceType } from "../data/mock";

function formatKES(amount) {
  return `KES ${amount.toLocaleString()}`;
}

const CHART_COLORS = ["#d97706", "#f59e0b", "#10b981", "#6366f1"];

const CustomTooltip = ({ active, payload, label }) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-white dark:bg-[#1e293b] border border-gray-200 dark:border-white/10 rounded-lg px-3 py-2 text-xs shadow-lg">
      <p className="font-medium text-gray-800 dark:text-white mb-1">{label}</p>
      {payload.map((p, i) => (
        <p key={i} style={{ color: p.color }}>{p.name}: {formatKES(p.value)}</p>
      ))}
    </div>
  );
};

function exportToCSV(data, filename) {
  if (data.length === 0) return;
  const headers = Object.keys(data[0]);
  const csv = [headers.join(","), ...data.map((row) => headers.map((h) => `"${String(row[h] || "").replace(/"/g, '""')}"`).join(","))].join("\n");
  const blob = new Blob([csv], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function generatePDF(title, content) {
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(`
    <html><head><title>${title}</title>
    <style>
      body { font-family: system-ui, sans-serif; padding: 40px; color: #1e293b; }
      h1 { font-size: 20px; margin-bottom: 4px; }
      .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; font-size: 13px; }
      th { text-align: left; padding: 8px 12px; border-bottom: 2px solid #e2e8f0; color: #64748b; font-size: 11px; text-transform: uppercase; }
      td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; }
      .amount { text-align: right; font-weight: 600; }
      .total { font-weight: 700; border-top: 2px solid #1e293b; }
      .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; }
      .badge-paid { background: #dcfce7; color: #166534; }
      .badge-pending { background: #fef3c7; color: #92400e; }
      .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; }
    </style></head><body>
    ${content}
    <p class="footer">Generated by FrameStudio Dashboard · ${new Date().toLocaleDateString()}</p>
    </body></html>
  `);
  w.document.close();
  w.print();
}

export default function Reports() {
  const { clients, income, invoices, expenses } = useData();
  const [activeReport, setActiveReport] = useState("monthly");
  const [clientFilter, setClientFilter] = useState("all");

  const totalIncome = income.reduce((s, i) => s + i.amount, 0);
  const totalExpenses = expenses.reduce((s, e) => s + e.amount, 0);
  const profit = totalIncome - totalExpenses;

  const cumulativeData = monthlyRevenue.reduce((acc, curr) => {
    const prev = acc.length > 0 ? acc[acc.length - 1].cumulative : 0;
    acc.push({ month: curr.month, cumulative: prev + curr.revenue });
    return acc;
  }, []);

  const outstandingInvoices = invoices.filter((i) => i.status === "sent" || i.status === "partial" || i.status === "overdue");
  const totalOutstanding = outstandingInvoices.reduce((s, i) => {
    if (i.status === "overdue" || i.status === "sent") return s + i.amount;
    const paid = income.filter((inc) => inc.clientName === i.clientName).reduce((p, inc) => p + inc.amount, 0);
    return s + (i.amount - paid);
  }, 0);

  const generateMonthlyReport = () => {
    const content = `
      <h1>Monthly Revenue Report</h1>
      <p class="meta">${new Date().toLocaleDateString()} · Last 6 months</p>
      <table>
        <tr><th>Month</th><th>Revenue</th><th>Collected</th><th>Outstanding</th></tr>
        ${monthlyComparison.map((m) => `<tr><td>${m.month}</td><td class="amount">${formatKES(monthlyRevenue.find((r) => r.month === m.month)?.revenue || 0)}</td><td class="amount">${formatKES(m.collected)}</td><td class="amount">${formatKES(m.outstanding)}</td></tr>`).join("")}
        <tr class="total"><td>Total</td><td class="amount">${formatKES(monthlyRevenue.reduce((s, m) => s + m.revenue, 0))}</td><td class="amount">${formatKES(monthlyComparison.reduce((s, m) => s + m.collected, 0))}</td><td class="amount">${formatKES(monthlyComparison.reduce((s, m) => s + m.outstanding, 0))}</td></tr>
      </table>
      <p style="margin-top:16px;font-size:13px;color:#64748b;">Profit: ${formatKES(profit)} · Margin: ${totalIncome > 0 ? ((profit / totalIncome) * 100).toFixed(1) : 0}%</p>
    `;
    generatePDF("Monthly Revenue Report", content);
  };

  const generateClientReport = () => {
    const targetClients = clientFilter === "all" ? clients : clients.filter((c) => c.name === clientFilter);
    const content = `
      <h1>Client Project Summary</h1>
      <p class="meta">${clientFilter === "all" ? "All clients" : clientFilter} · ${new Date().toLocaleDateString()}</p>
      ${targetClients.map((c) => {
        const cinvoice = income.filter((i) => i.clientName === c.name);
        const totalPaid = cinvoice.reduce((s, i) => s + i.amount, 0);
        const owing = c.projectValue - totalPaid;
        return `
          <div style="margin-bottom:24px;padding-bottom:16px;border-bottom:1px solid #e2e8f0;">
            <h2 style="font-size:16px;margin:0 0 4px;">${c.name}</h2>
            <p style="font-size:12px;color:#64748b;margin:0 0 8px;">${c.business} · ${c.whatWasBuilt}</p>
            <table>
              <tr><th>Metric</th><th class="amount">Value</th></tr>
              <tr><td>Project Value</td><td class="amount">${formatKES(c.projectValue)}</td></tr>
              <tr><td>Total Paid</td><td class="amount">${formatKES(totalPaid)}</td></tr>
              <tr><td>Outstanding</td><td class="amount">${formatKES(owing)}</td></tr>
              <tr><td>Status</td><td class="amount"><span class="badge badge-${c.invoiceStatus === "paid" ? "paid" : "pending"}">${c.invoiceStatus}</span></td></tr>
            </table>
            ${cinvoice.length > 0 ? `
              <h3 style="font-size:13px;margin:12px 0 4px;">Payment History</h3>
              <table>
                <tr><th>Date</th><th>Description</th><th class="amount">Amount</th></tr>
                ${cinvoice.map((inv) => `<tr><td>${inv.date}</td><td>${inv.description}</td><td class="amount">${formatKES(inv.amount)}</td></tr>`).join("")}
              </table>
            ` : ""}
          </div>
        `;
      }).join("")}
    `;
    generatePDF("Client Project Summary", content);
  };

  const generateOutstandingReport = () => {
    const content = `
      <h1>Outstanding Invoices Report</h1>
      <p class="meta">${new Date().toLocaleDateString()} · Total outstanding: ${formatKES(totalOutstanding)}</p>
      ${outstandingInvoices.length === 0 ? "<p>No outstanding invoices</p>" : `
        <table>
          <tr><th>Client</th><th>Description</th><th>Status</th><th class="amount">Amount</th></tr>
          ${outstandingInvoices.map((inv) => `<tr><td>${inv.clientName}</td><td>${inv.description}</td><td><span class="badge badge-pending">${inv.status}</span></td><td class="amount">${formatKES(inv.amount)}</td></tr>`).join("")}
          <tr class="total"><td colspan="3">Total Outstanding</td><td class="amount">${formatKES(totalOutstanding)}</td></tr>
        </table>
      `}
    `;
    generatePDF("Outstanding Invoices Report", content);
  };

  return (
    <PageLayout title="Reports">
      <div className="max-w-5xl mx-auto space-y-5">
        <div className="flex items-center gap-1 bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-lg p-0.5 shadow-sm w-fit">
          {["monthly", "clients", "outstanding"].map((tab) => (
            <button key={tab} onClick={() => setActiveReport(tab)} className={`px-3 py-1.5 text-xs rounded-md transition-all ${activeReport === tab ? "bg-amber-500/10 text-amber-600 dark:text-amber-400 font-medium" : "text-gray-400 dark:text-slate-500 hover:text-gray-600"}`}>
              {tab === "monthly" ? "Monthly Revenue" : tab === "clients" ? "Per Client" : "Outstanding"}
            </button>
          ))}
        </div>

        {activeReport === "monthly" && (
          <>
            <div className="flex items-center justify-between">
              <p className="text-sm text-gray-400 dark:text-slate-500">{income.length} transactions · Last 6 months</p>
              <button onClick={generateMonthlyReport} className="flex items-center gap-1.5 text-xs font-medium bg-amber-600 text-white rounded-lg px-3 py-1.5 hover:bg-amber-500 transition-colors">
                <IoDocumentTextOutline size={12} /> Generate report
              </button>
            </div>
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
              <div className="bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-2xl p-4 shadow-sm">
                <p className="text-xs text-gray-400 dark:text-slate-500">Total revenue</p>
                <p className="text-lg font-bold text-gray-900 dark:text-white">{formatKES(totalIncome)}</p>
              </div>
              <div className="bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-2xl p-4 shadow-sm">
                <p className="text-xs text-gray-400 dark:text-slate-500">Total expenses</p>
                <p className="text-lg font-bold text-red-600">{formatKES(totalExpenses)}</p>
              </div>
              <div className="bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-2xl p-4 shadow-sm">
                <p className="text-xs text-gray-400 dark:text-slate-500">Net profit</p>
                <p className={`text-lg font-bold ${profit >= 0 ? "text-green-600" : "text-red-600"}`}>{formatKES(profit)}</p>
              </div>
              <div className="bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-2xl p-4 shadow-sm">
                <p className="text-xs text-gray-400 dark:text-slate-500">Profit margin</p>
                <p className="text-lg font-bold text-gray-900 dark:text-white">{totalIncome > 0 ? ((profit / totalIncome) * 100).toFixed(1) : 0}%</p>
              </div>
            </div>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              <ChartCard title="Revenue vs Outstanding" subtitle="Monthly comparison">
                <div className="flex items-center justify-between mb-2">
                  <p className="text-xs text-gray-400 dark:text-slate-500">Click to export CSV</p>
                  <button onClick={() => exportToCSV(monthlyComparison, "monthly-revenue.csv")} className="flex items-center gap-1 text-xs text-amber-600 dark:text-amber-400 hover:underline"><IoDownloadOutline size={12} /> CSV</button>
                </div>
                <ResponsiveContainer width="100%" height={240}>
                  <BarChart data={monthlyComparison}>
                    <XAxis dataKey="month" tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
                    <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`} />
                    <Tooltip content={<CustomTooltip />} />
                    <Bar dataKey="collected" fill="#d97706" radius={[4, 4, 0, 0]} name="Collected" />
                    <Bar dataKey="outstanding" fill="#f59e0b" radius={[4, 4, 0, 0]} name="Outstanding" />
                  </BarChart>
                </ResponsiveContainer>
              </ChartCard>
              <ChartCard title="Cumulative revenue" subtitle="Running total">
                <ResponsiveContainer width="100%" height={240}>
                  <LineChart data={cumulativeData}>
                    <XAxis dataKey="month" tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
                    <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} tickFormatter={(v) => `${(v / 1000).toFixed(0)}k`} />
                    <Tooltip content={<CustomTooltip />} />
                    <Line type="monotone" dataKey="cumulative" stroke="#d97706" strokeWidth={2.5} dot={{ fill: "#d97706", r: 3 }} name="Total" />
                  </LineChart>
                </ResponsiveContainer>
              </ChartCard>
            </div>
          </>
        )}

        {activeReport === "clients" && (
          <>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <select value={clientFilter} onChange={(e) => setClientFilter(e.target.value)} className="text-sm border border-gray-200 dark:border-white/10 rounded-lg px-3 py-1.5 bg-white dark:bg-[#0f172a] text-gray-700 dark:text-slate-300 focus:outline-none focus:border-amber-400">
                  <option value="all">All clients</option>
                  {clients.map((c) => <option key={c.id} value={c.name}>{c.name}</option>)}
                </select>
                <p className="text-sm text-gray-400 dark:text-slate-500">{clientFilter === "all" ? clients.length : 1} client{(clientFilter === "all" && clients.length !== 1) ? "s" : ""}</p>
              </div>
              <button onClick={generateClientReport} className="flex items-center gap-1.5 text-xs font-medium bg-amber-600 text-white rounded-lg px-3 py-1.5 hover:bg-amber-500 transition-colors">
                <IoDocumentTextOutline size={12} /> Generate report
              </button>
            </div>
            <div className="space-y-3">
              {(clientFilter === "all" ? clients : clients.filter((c) => c.name === clientFilter)).map((client) => {
                const cinvoice = income.filter((i) => i.clientName === client.name);
                const totalPaid = cinvoice.reduce((s, i) => s + i.amount, 0);
                const owing = client.projectValue - totalPaid;
                return (
                  <div key={client.id} className="bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-2xl p-4 shadow-sm">
                    <div className="flex items-center justify-between mb-2">
                      <div>
                        <h3 className="text-sm font-semibold text-gray-900 dark:text-white">{client.name}</h3>
                        <p className="text-xs text-gray-400 dark:text-slate-500">{client.business} · {client.whatWasBuilt}</p>
                      </div>
                      <button onClick={() => exportToCSV(cinvoice, `${client.name.replace(/\s+/g, "-").toLowerCase()}-payments.csv`)} className="flex items-center gap-1 text-xs text-amber-600 dark:text-amber-400 hover:underline"><IoDownloadOutline size={12} /> CSV</button>
                    </div>
                    <div className="grid grid-cols-3 gap-4 text-sm mt-3 pt-3 border-t border-gray-50 dark:border-white/5">
                      <div>
                        <p className="text-xs text-gray-400 dark:text-slate-500">Project value</p>
                        <p className="font-semibold text-gray-900 dark:text-white">{formatKES(client.projectValue)}</p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-400 dark:text-slate-500">Paid</p>
                        <p className="font-semibold text-green-600">{formatKES(totalPaid)}</p>
                      </div>
                      <div>
                        <p className="text-xs text-gray-400 dark:text-slate-500">Outstanding</p>
                        <p className={`font-semibold ${owing > 0 ? "text-red-600" : "text-gray-900 dark:text-white"}`}>{formatKES(owing)}</p>
                      </div>
                    </div>
                    {cinvoice.length > 0 && (
                      <div className="mt-3 pt-3 border-t border-gray-50 dark:border-white/5">
                        <p className="text-xs font-medium text-gray-500 dark:text-slate-400 mb-1">Payment history</p>
                        <div className="space-y-1">
                          {cinvoice.map((entry) => (
                            <div key={entry.id} className="flex items-center justify-between text-xs">
                              <span className="text-gray-600 dark:text-slate-400">{entry.date} · {entry.description}</span>
                              <span className="font-medium text-gray-800 dark:text-white">{formatKES(entry.amount)}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </>
        )}

        {activeReport === "outstanding" && (
          <>
            <div className="flex items-center justify-between">
              <p className="text-sm text-gray-400 dark:text-slate-500">{outstandingInvoices.length} outstanding invoices · {formatKES(totalOutstanding)} total</p>
              <button onClick={generateOutstandingReport} className="flex items-center gap-1.5 text-xs font-medium bg-amber-600 text-white rounded-lg px-3 py-1.5 hover:bg-amber-500 transition-colors">
                <IoDocumentTextOutline size={12} /> Generate report
              </button>
            </div>
            {outstandingInvoices.length === 0 ? (
              <div className="bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-2xl p-8 text-center shadow-sm">
                <p className="text-sm text-gray-500 dark:text-slate-400">No outstanding invoices!</p>
              </div>
            ) : (
              <div className="bg-white dark:bg-[#0f172a] border border-gray-100 dark:border-white/10 rounded-2xl overflow-hidden shadow-sm">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-gray-100 dark:border-white/10">
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-400 dark:text-slate-500">Client</th>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-400 dark:text-slate-500">Description</th>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-400 dark:text-slate-500">Status</th>
                      <th className="text-left px-4 py-3 text-xs font-medium text-gray-400 dark:text-slate-500">Due</th>
                      <th className="text-right px-4 py-3 text-xs font-medium text-gray-400 dark:text-slate-500">Amount</th>
                    </tr>
                  </thead>
                  <tbody>
                    {outstandingInvoices.map((inv) => (
                      <tr key={inv.id} className="border-b border-gray-50 dark:border-white/5 last:border-0">
                        <td className="px-4 py-3 font-medium text-gray-800 dark:text-white">{inv.clientName}</td>
                        <td className="px-4 py-3 text-xs text-gray-500 dark:text-slate-400">{inv.description}</td>
                        <td className="px-4 py-3">
                          <span className={`text-[10px] px-1.5 py-0.5 rounded font-medium ${inv.status === "overdue" ? "bg-red-500/10 text-red-600" : "bg-amber-500/10 text-amber-600"}`}>
                            {inv.status.charAt(0).toUpperCase() + inv.status.slice(1)}
                          </span>
                        </td>
                        <td className="px-4 py-3 text-xs text-gray-500 dark:text-slate-400">{inv.due || "—"}</td>
                        <td className="px-4 py-3 text-right font-semibold text-gray-900 dark:text-white">{formatKES(inv.amount)}</td>
                      </tr>
                    ))}
                    <tr className="bg-gray-50 dark:bg-white/[0.03]">
                      <td colSpan={4} className="px-4 py-3 text-sm font-semibold text-gray-800 dark:text-white">Total Outstanding</td>
                      <td className="px-4 py-3 text-right font-bold text-red-600">{formatKES(totalOutstanding)}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            )}
          </>
        )}
      </div>
    </PageLayout>
  );
}
